// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzocnAWqoy1z5YSh0bpFy5b36qOSY3H6k',
    appId: '1:615197330554:web:bcb75ee756d7cee990ffc3',
    messagingSenderId: '615197330554',
    projectId: 'productivity-app-707ba',
    authDomain: 'productivity-app-707ba.firebaseapp.com',
    storageBucket: 'productivity-app-707ba.appspot.com',
    measurementId: 'G-THF20QCJDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8A1Cns03Tvgpt-jPSCKBLpB4jP-fveWM',
    appId: '1:615197330554:android:ab934b296002013a90ffc3',
    messagingSenderId: '615197330554',
    projectId: 'productivity-app-707ba',
    storageBucket: 'productivity-app-707ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGbEbrSxunTIM27VUmXRghezDC93OWPMU',
    appId: '1:615197330554:ios:7b01040920b147b390ffc3',
    messagingSenderId: '615197330554',
    projectId: 'productivity-app-707ba',
    storageBucket: 'productivity-app-707ba.appspot.com',
    iosClientId: '615197330554-q2a06ha394np4dskpn8eepg734hsin43.apps.googleusercontent.com',
    iosBundleId: 'com.example.productivityApp',
  );
}
